spring:
  profiles: dev
  jpa:
    hibernate:
      ddlAuto: update
      namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: true
  #  liquibase:
  #    change-log: classpath:/liquibase/master.xml
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
server:
  port: 6060
  ssl:
    ##    prod
    key-store: classpath:cert/keystore.jks
    #    key-store: /etc/letsencrypt/live/www.lockbridges.com/keystoreNew.p12
    key-store-password: helloearth6
    #    keyStoreType: PKCS12
    #    key-password: helloearth6
    keyAlias: selfsigned
database:
  driverClassName: org.mariadb.jdbc.Driver
  jdbcUrl: jdbc:mariadb://localhost:3306/lb?useUnicode=true&character_set_server=utf8mb4
  username: root
  password: root
  poolSize: 60
  autoCommit: false
mail:
  starttls: true
  host: smtp.mail.yahoo.com
  port: 587
  username: alex.timis95@yahoo.com
  password: fordevelopment6
  from: alex.timis95@yahoo.com
facebook:
  clientId: 227796454748370
  clientSecret: 99b7d10633ccea8a8a8c7731fdcaffa7
aws:
  access.key: AKIAJFAJZOWMKCU3CMUA
  secret.key: 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
  #  region: eu-central-1
  region: eu-west-1
  ###AWS STREAMING
  upload.expiration.seconds: 3600
  s3.url: http://s3-eu-west-1.amazonaws.com/
  video.bucket: lock-s3-video
  hls.bucket: lock-s3-video-hls
  thumbnail.bucket: lock-s3-thumbnail
  encoding.pipeline.id: 1559041615636-v1q2s4
  encoding.segment.duration.seconds: 10
  encoding.notification.queue.url: https://sqs.eu-west-1.amazonaws.com/634422706002/lock-queue
  system.preset.hls.400k.id: 1351620000001-200050
  system.preset.hls.600k.id: 1351620000001-200040
  system.preset.hls.1m.id: 1351620000001-200030
  system.preset.hls.2m.id: 1351620000001-200010
  cloudfront.distribution.url: dbdee3ttou8ph.cloudfront.net
    #  bucket:
    #    category: lock-s3-bucket/Category
    #    template: lock-s3-bucket/Template
    #    partiallyErasedTemplate: lock-s3-bucket/PartiallyErasedTemplate
    #    partiallyErasedTemplateWithText: lock-s3-bucket/PartiallyErasedTemplateWithText
    #    bridge: lock-s3-bucket/Bridge
    #    glitterErasedTemplate: lock-s3-bucket/GlitterErasedTemplate
  bucket:
    category: lock-s3-pictures/Category
    template: lock-s3-pictures/Template
    partiallyErasedTemplate: lock-s3-pictures/PartiallyErasedTemplate
    partiallyErasedTemplateWithText: lock-s3-pictures/PartiallyErasedTemplateWithText
    bridge: lock-s3-pictures/Bridge
    glitterErasedTemplate: lock-s3-pictures/GlitterErasedTemplate
file:
  domain: https://localhost:6060
  #    domain: https://api.lockbridges.com
  storageType: AWS_S3
paypal:
  public.key: zph4yfbfn5j55796
  private.key: ab7e503584b183d78f198b85eb9fa7fc
  merchant.id: xm25gj6df6n85xqx

stripe:
  public.key: pk_test_9Mmg0Q2xkKB9TR2bDfx71Dnb
  secret.key: sk_test_DdzEdTIMYETHliRVtbKB6aJX

panelMaxLocks: 30

