spring:
  profiles: dev
  jpa:
    hibernate:
      ddlAuto: create
      namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: true
#  liquibase:
#    change-log: classpath:/liquibase/master.xml
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB
server:
  port: 6060
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: helloearth6
    key-password: helloearth6
database:
  driverClassName: org.mariadb.jdbc.Driver
  jdbcUrl: jdbc:mariadb://localhost:3306/lb
  username: root
  password: root
  poolSize: 60
  autoCommit: false
mail:
  starttls: true
  host: smtp.mail.yahoo.com
  port: 587
  username: alex.timis95@yahoo.com
  password: fordevelopment6
  from: alex.timis95@yahoo.com
facebook:
  clientId: 227796454748370
  clientSecret: 99b7d10633ccea8a8a8c7731fdcaffa7